#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
from os import environ
from DashBoard import app

if __name__ == '__main__':
    HOST = environ.get('SERVER_HOST', 'localhost')
    print(os.getcwd())
    try:
        PORT = int(environ.get('SERVER_PORT', '5555'))
    except ValueError:
        PORT = 5555
    app.run(HOST, PORT, debug=True)
